Show version on REPL startup
kubukoz/spotify-next pull request #172
Opened 2021-04-21 13:28 UTC by toshihidetagami

This pull request closes issue #7.

2021-04-21 14:43 UTC, kubukoz requested changes
Thanks! Just some small changes I'd like to see here.

2021-04-21 14:43 UTC, kubukoz commented on src/main/scala/com/kubukoz/next/Main.scala
> +    fs2.Stream.exec(IO.println(s"Loading REPL...version: ${BuildInfo.version.takeWhile(_ != '+')}")) ++
IMO we can print the full version. There isn't going to be a `+` in the tagged releases :)

2021-04-21 14:43 UTC, kubukoz commented on src/main/scala/com/kubukoz/next/Main.scala
> +    fs2.Stream.exec(IO.println(s"Loading REPL...version: ${BuildInfo.version.takeWhile(_ != '+')}")) ++
Also, about the format, I would print this in the welcome message:

```
Loading REPL...
Welcome to the spotify-next ${BuildInfo.version} REPL! Type in a command to begin
```

This is a couple lines below.

2021-04-21 14:43 UTC, kubukoz commented on project/plugins.sbt
> +addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
We already have sbt-dynver thanks to the sbt-ci-release dependency.

2021-04-21 14:43 UTC, kubukoz commented on build.sbt
> +      buildInfoKeys := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
`version` alone is good enough for now

2021-04-27 13:35 UTC, toshihidetagami commented
Thanks for the review! I added a commit.

2021-04-27 13:55 UTC, toshihidetagami commented
Thanks for the review! I added commits.

2021-04-27 18:55 UTC, kubukoz approved these changes
Thank you!

2021-04-27 18:58 UTC, kubukoz commented
Rebased and merged locally.

2021-04-27 18:58 UTC, closed without merging